'use strict';

const { randomUUID } = require('crypto');

/**
 * katalonScaffold.service.js
 *
 * Generates a real Katalon Studio-compatible project structure on disk.
 *
 * Katalon folder spec (compatible with Katalon Studio 8.x / 9.x):
 *
 *  <ProjectName>/
 *  ├── Profiles/
 *  │   └── default.glbl
 *  ├── Test Cases/
 *  ├── Test Suites/
 *  ├── Object Repository/
 *  ├── Data Files/
 *  ├── Checkpoints/
 *  ├── Keywords/
 *  ├── Test Listeners/
 *  ├── Reports/
 *  ├── Include/
 *  │   ├── config/
 *  │   │   └── log4j.properties
 *  │   ├── features/
 *  │   └── scripts/
 *  │       └── groovy/
 *  ├── Plugins/
 *  ├── Scripts/
 *  ├── .gitignore
 *  ├── README.md
 *  └── <ProjectName>.prj     ← minimal Katalon .prj XML
 *
 * This module is pure Node.js (no external deps) and is synchronous
 * so callers can keep error-handling simple.
 */

const fs   = require('fs');
const path = require('path');

// ────────────────────────────────────────────────────────────────────────────
// Folder list
// ────────────────────────────────────────────────────────────────────────────

/** All top-level folders to create under the project root. */
const KATALON_FOLDERS = [
  'Profiles',
  'Test Cases',
  'Test Suites',
  'Object Repository',
  'Data Files',
  'Checkpoints',
  'Keywords',
  'Test Listeners',
  'Reports',
  'Include',
  'Include/config',
  'Include/features',
  'Include/scripts',
  'Include/scripts/groovy',
  'Plugins',
  'Scripts',
];

// ────────────────────────────────────────────────────────────────────────────
// File templates
// ────────────────────────────────────────────────────────────────────────────

/**
 * Katalon .prj file (XML format expected by Katalon Studio / KRE 8–11).
 * Katalon 11 requires pageLoadTimeout and pageLoadTimeoutDefault to be
 * present — without them the ProjectEntity XStream deserializer returns
 * null, causing a NullPointerException in ProjectFileServiceManager:99.
 */
function buildPrjXml(projectName) {
  const uuid = randomUUID();
  return `<?xml version="1.0" encoding="UTF-8"?>
<ProjectEntity>
   <description></description>
   <id>${uuid}</id>
   <name>${escapeXml(projectName)}</name>
   <defaultProfile>default</defaultProfile>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
</ProjectEntity>
`;
}

/**
 * Katalon global variable profile — must exist for the Runtime Engine
 * to launch without errors.
 */
function buildDefaultGlbl() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<GlobalVariableEntities>
   <defaultProfile>true</defaultProfile>
   <description></description>
   <entities/>
   <name>default</name>
</GlobalVariableEntities>
`;
}

/**
 * Minimal log4j.properties required by Katalon's Include/config directory.
 */
function buildLog4jProperties() {
  return `# Katalon Studio log4j configuration
log4j.rootLogger=INFO, stdout, file

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{HH:mm:ss} %-5p %c{1} - %m%n

log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.File=katalon.log
log4j.appender.file.MaxFileSize=5MB
log4j.appender.file.MaxBackupIndex=3
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c - %m%n
`;
}

/**
 * Standard .gitignore for a Katalon project.
 */
function buildGitignore() {
  return `# Katalon generated
/Reports/
/Logs/
*.log

# OS
.DS_Store
Thumbs.db

# IDE
/.idea/
/.vscode/

# Katalon temp
/Screenshots/
/Output/
`;
}

/**
 * Human-readable README placed in the project root.
 */
function buildReadme(projectName, description) {
  const now = new Date().toISOString().slice(0, 10);
  return `# ${projectName}

${description ? description + '\n' : ''}
> Generated by Automation Testing Management Platform on ${now}.

## Getting Started

1. Open **Katalon Studio** → File → Open Project → select this folder.
2. Or run via Katalon Runtime Engine:

\`\`\`bash
katalonc -projectPath="${projectName}.prj" -browserType=Chrome -retry=0
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── Profiles/          # Global variable profiles
│   └── default.glbl
├── Test Cases/        # .tc test case files
├── Test Suites/       # .ts test suite files
├── Object Repository/ # .rs object files
├── Data Files/        # Test data (CSV, Excel)
├── Checkpoints/       # DB/image checkpoints
├── Keywords/          # Custom Groovy keywords
├── Test Listeners/    # Hooks (before/after suite/case)
├── Reports/           # Execution reports (git-ignored)
├── Include/           # BDD features & Groovy scripts
├── Plugins/           # Katalon plugins
└── Scripts/           # Auto-generated test scripts
\`\`\`
`;
}

// ────────────────────────────────────────────────────────────────────────────
// Validation helpers
// ────────────────────────────────────────────────────────────────────────────

/**
 * Characters that are forbidden in directory names on Windows/Linux.
 * We apply the stricter Windows set so the project is portable.
 */
const FORBIDDEN_NAME_CHARS = /[<>:"/\\|?*\x00-\x1f]/;

function scaffoldError(message, code = 'SCAFFOLD_ERROR') {
  const err = new Error(message);
  err.statusCode = 400;
  err.code = code;
  return err;
}

function escapeXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Validate that `saveDirectory` exists, is writable, and that the resulting
 * project folder (`saveDirectory/<projectName>`) does not already exist.
 *
 * @param {string} saveDirectory  Absolute path to the parent folder
 * @param {string} projectName    Sanitised project name
 * @returns {string}              Resolved absolute project root path
 */
function validateScaffoldInputs(saveDirectory, projectName) {
  // ── Project name checks ─────────────────────────────────────────────────
  if (!projectName || typeof projectName !== 'string') {
    throw scaffoldError('Tên project không hợp lệ.');
  }
  const trimmedName = projectName.trim();
  if (!trimmedName) {
    throw scaffoldError('Tên project không được để trống.');
  }
  if (trimmedName.length > 100) {
    throw scaffoldError('Tên project không được vượt quá 100 ký tự.');
  }
  if (FORBIDDEN_NAME_CHARS.test(trimmedName)) {
    throw scaffoldError(
      'Tên project chứa ký tự không hợp lệ. Không được dùng: < > : " / \\ | ? *'
    );
  }

  // ── Save directory checks ───────────────────────────────────────────────
  if (!saveDirectory || typeof saveDirectory !== 'string') {
    throw scaffoldError('Đường dẫn lưu project không hợp lệ.');
  }
  const resolvedSaveDir = path.resolve(saveDirectory.trim());

  if (!fs.existsSync(resolvedSaveDir)) {
    throw scaffoldError(
      `Thư mục lưu project không tồn tại: "${resolvedSaveDir}". Hãy chọn thư mục đã tồn tại.`,
      'DIR_NOT_FOUND'
    );
  }

  let dirStat;
  try {
    dirStat = fs.statSync(resolvedSaveDir);
  } catch (err) {
    throw scaffoldError(
      `Không thể truy cập thư mục: "${resolvedSaveDir}". Chi tiết: ${err.message}`,
      'DIR_INACCESSIBLE'
    );
  }

  if (!dirStat.isDirectory()) {
    throw scaffoldError(
      `Đường dẫn không phải thư mục: "${resolvedSaveDir}".`,
      'NOT_A_DIRECTORY'
    );
  }

  try {
    fs.accessSync(resolvedSaveDir, fs.constants.W_OK);
  } catch {
    throw scaffoldError(
      `Không có quyền ghi vào thư mục: "${resolvedSaveDir}". Hãy chọn thư mục khác hoặc chạy ứng dụng với quyền phù hợp.`,
      'NO_WRITE_PERMISSION'
    );
  }

  // ── Duplicate project folder check ──────────────────────────────────────
  const projectRoot = path.join(resolvedSaveDir, trimmedName);
  if (fs.existsSync(projectRoot)) {
    throw scaffoldError(
      `Thư mục project "${trimmedName}" đã tồn tại tại "${resolvedSaveDir}". Hãy đổi tên hoặc chọn thư mục lưu khác.`,
      'PROJECT_FOLDER_EXISTS'
    );
  }

  return projectRoot;
}

// ────────────────────────────────────────────────────────────────────────────
// Main scaffold function
// ────────────────────────────────────────────────────────────────────────────

/**
 * Generate a Katalon-compatible project skeleton on disk.
 *
 * @param {object} options
 * @param {string} options.projectName    Name of the project (becomes folder name)
 * @param {string} options.saveDirectory  Parent directory where the project folder is created
 * @param {string} [options.description]  Optional description for README
 *
 * @returns {{
 *   projectRoot: string,
 *   katalon_project_path: string,
 *   foldersCreated: string[],
 *   filesCreated: string[]
 * }}
 */
function generateKatalonProject({ projectName, saveDirectory, description = '' }) {
  // 1. Validate inputs + resolve final project root path
  const projectRoot = validateScaffoldInputs(saveDirectory, projectName);
  const trimmedName = projectName.trim();

  const foldersCreated = [];
  const filesCreated   = [];

  try {
    // 2. Create project root
    fs.mkdirSync(projectRoot, { recursive: true });
    foldersCreated.push(projectRoot);

    // 3. Create all sub-folders
    for (const folderRelPath of KATALON_FOLDERS) {
      const fullPath = path.join(projectRoot, folderRelPath);
      fs.mkdirSync(fullPath, { recursive: true });
      foldersCreated.push(fullPath);
    }

    // 4. Write files
    const writeFile = (relPath, content) => {
      const fullPath = path.join(projectRoot, relPath);
      // Ensure parent directory exists (for nested files)
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, content, 'utf8');
      filesCreated.push(fullPath);
    };

    // 4a. Katalon .prj descriptor
    writeFile(`${trimmedName}.prj`, buildPrjXml(trimmedName));

    // 4b. Default global variable profile
    writeFile('Profiles/default.glbl', buildDefaultGlbl());

    // 4c. log4j.properties
    writeFile('Include/config/log4j.properties', buildLog4jProperties());

    // 4d. .gitignore
    writeFile('.gitignore', buildGitignore());

    // 4e. README
    writeFile('README.md', buildReadme(trimmedName, description));

  } catch (err) {
    // Roll back: remove anything we created so far
    try {
      if (fs.existsSync(projectRoot)) {
        fs.rmSync(projectRoot, { recursive: true, force: true });
      }
    } catch {
      // best-effort rollback — ignore secondary errors
    }

    // Re-throw scaffold errors as-is; wrap OS errors
    if (err.code && err.statusCode === 400) throw err;

    // Map common OS error codes to friendly messages
    if (err.code === 'ENOSPC') {
      throw scaffoldError('Đĩa cứng đầy. Không thể tạo project.', 'DISK_FULL');
    }
    if (err.code === 'ENAMETOOLONG') {
      throw scaffoldError(
        'Đường dẫn quá dài. Hãy chọn thư mục lưu gần thư mục gốc hơn hoặc rút ngắn tên project.',
        'PATH_TOO_LONG'
      );
    }
    if (err.code === 'EACCES' || err.code === 'EPERM') {
      throw scaffoldError(
        `Không có quyền tạo thư mục project tại "${projectRoot}". Chi tiết: ${err.message}`,
        'PERMISSION_DENIED'
      );
    }

    const wrapped = new Error(`Lỗi tạo Katalon project: ${err.message}`);
    wrapped.statusCode = 500;
    throw wrapped;
  }

  return {
    projectRoot,
    /** Absolute path stored in DB — equal to the project root folder */
    katalon_project_path: projectRoot,
    foldersCreated,
    filesCreated,
  };
}

module.exports = {
  generateKatalonProject,
  validateScaffoldInputs,
  KATALON_FOLDERS,
};
