'use strict';

/**
 * mochaScaffold.service.js
 *
 * Replaces katalonScaffold.service.js.
 * Generates a Playwright + Mocha + Chai project skeleton on disk.
 *
 * Folder layout:
 *   <ProjectRoot>/
 *   ├── tests/
 *   │   ├── suites/        # Suite .spec.js files (runner files)
 *   │   ├── cases/         # Individual test case .spec.js files
 *   │   ├── generated/     # AI-generated specs
 *   │   └── locators/      # Locator JSON files (replaces Object Repository)
 *   ├── reports/           # Mochawesome report output
 *   ├── screenshots/       # Playwright screenshot output
 *   ├── .mocharc.cjs       # Mocha configuration
 *   ├── package.json       # Project descriptor (deps listed for reference)
 *   ├── .gitignore
 *   └── README.md
 *
 * Note: test execution uses the backend's own node_modules — the project's
 * package.json documents dependencies but npm install is not required.
 */

const fs   = require('fs');
const path = require('path');

const MOCHA_FOLDERS = [
  'tests',
  'tests/suites',
  'tests/cases',
  'tests/generated',
  'tests/locators',
  'reports',
  'screenshots',
];

// ── File templates ────────────────────────────────────────────────────────────

function buildPackageJson(projectName) {
  return JSON.stringify({
    name:    projectName.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    private: true,
    scripts: {
      test:        'mocha tests/cases/**/*.spec.js --timeout 30000 --exit',
      'test:suite': 'mocha tests/suites/**/*.spec.js --timeout 30000 --exit',
    },
    dependencies: {
      chai:         '^4.3.10',
      mocha:        '^11.0.0',
      mochawesome:  '^7.1.3',
      playwright:   '^1.40.0',
    },
  }, null, 2) + '\n';
}

function buildMochaRc() {
  return `'use strict';
module.exports = {
  timeout:  30000,
  exit:     true,
  reporter: 'mochawesome',
  'reporter-options': [
    'reportDir=reports',
    'reportFilename=mocha-report',
    'quiet=true',
    'overwrite=true',
  ].join(','),
};
`;
}

function buildGitignore() {
  return `# Reports and runtime artifacts
/reports/
/screenshots/
*.log

# Dependencies (project uses backend node_modules)
/node_modules/

# OS
.DS_Store
Thumbs.db

# IDE
/.idea/
/.vscode/
`;
}

function buildReadme(projectName, description) {
  const date = new Date().toISOString().slice(0, 10);
  return `# ${projectName}

${description ? description + '\n' : ''}
> Generated by YetiForce QA Automation Platform on ${date}.
> Engine: Playwright + Mocha + Chai

## Project Structure

\`\`\`
${projectName}/
├── tests/
│   ├── suites/      # Suite runner files (execute a group of tests)
│   ├── cases/       # Individual test case spec files
│   ├── generated/   # AI-generated test cases
│   └── locators/    # Element locator definitions (JSON)
├── reports/         # Mochawesome reports (git-ignored)
├── screenshots/     # Playwright screenshots (git-ignored)
├── .mocharc.cjs     # Mocha configuration
└── package.json     # Project metadata
\`\`\`

## Running Tests

Tests are executed via the YetiForce QA Platform Run Engine.

To run manually (requires Node.js and the platform backend running):

\`\`\`bash
# Run all test cases
mocha tests/cases/**/*.spec.js --timeout 30000 --exit

# Run a specific suite
mocha tests/suites/MySuite.spec.js --timeout 30000 --exit
\`\`\`
`;
}

function buildExampleSpec(projectName) {
  return `'use strict';
/**
 * Example Playwright + Mocha + Chai test.
 * Rename or replace with your actual test cases.
 */
const { chromium, firefox } = require('playwright');
const chai = require('chai');
const expect = chai.expect;

describe('Example Test Suite — ${projectName}', () => {
  let browser;
  let page;

  before(async () => {
    const browserType = process.env.TEST_BROWSER || 'chromium';
    const headless    = process.env.TEST_HEADLESS !== 'false';
    browser = await require('playwright')[browserType].launch({ headless });
    page    = await browser.newPage();
  });

  after(async () => {
    if (browser) await browser.close();
  });

  it('should load example.com', async () => {
    await page.goto('https://example.com');
    const title = await page.title();
    expect(title).to.include('Example');
  });
});
`;
}

// ── Validation ────────────────────────────────────────────────────────────────

const FORBIDDEN_CHARS = /[<>:"/\\|?*\x00-\x1f]/;

function scaffoldError(message, code = 'SCAFFOLD_ERROR') {
  const err = new Error(message);
  err.statusCode = 400;
  err.code = code;
  return err;
}

function validateScaffoldInputs(saveDirectory, projectName) {
  if (!projectName || typeof projectName !== 'string') {
    throw scaffoldError('Tên project không hợp lệ.');
  }
  const trimmedName = projectName.trim();
  if (!trimmedName) throw scaffoldError('Tên project không được để trống.');
  if (trimmedName.length > 100) throw scaffoldError('Tên project không được vượt quá 100 ký tự.');
  if (FORBIDDEN_CHARS.test(trimmedName)) {
    throw scaffoldError('Tên project chứa ký tự không hợp lệ. Không được dùng: < > : " / \\ | ? *');
  }

  if (!saveDirectory || typeof saveDirectory !== 'string') {
    throw scaffoldError('Đường dẫn lưu project không hợp lệ.');
  }
  const resolvedSaveDir = path.resolve(saveDirectory.trim());

  if (!fs.existsSync(resolvedSaveDir)) {
    throw scaffoldError(
      `Thư mục lưu project không tồn tại: "${resolvedSaveDir}".`,
      'DIR_NOT_FOUND',
    );
  }
  const dirStat = fs.statSync(resolvedSaveDir);
  if (!dirStat.isDirectory()) {
    throw scaffoldError(`Đường dẫn không phải thư mục: "${resolvedSaveDir}".`, 'NOT_A_DIRECTORY');
  }
  try { fs.accessSync(resolvedSaveDir, fs.constants.W_OK); } catch {
    throw scaffoldError(
      `Không có quyền ghi vào thư mục: "${resolvedSaveDir}".`,
      'NO_WRITE_PERMISSION',
    );
  }

  const projectRoot = path.join(resolvedSaveDir, trimmedName);
  if (fs.existsSync(projectRoot)) {
    throw scaffoldError(
      `Thư mục project "${trimmedName}" đã tồn tại tại "${resolvedSaveDir}".`,
      'PROJECT_FOLDER_EXISTS',
    );
  }
  return projectRoot;
}

// ── Main scaffold ─────────────────────────────────────────────────────────────

/**
 * Generate a Playwright + Mocha project skeleton on disk.
 *
 * @param {{ projectName, saveDirectory, description }} options
 * @returns {{ projectRoot, katalon_project_path, foldersCreated, filesCreated }}
 */
function generateMochaProject({ projectName, saveDirectory, description = '' }) {
  const projectRoot = validateScaffoldInputs(saveDirectory, projectName);
  const trimmedName = projectName.trim();

  const foldersCreated = [];
  const filesCreated   = [];

  try {
    fs.mkdirSync(projectRoot, { recursive: true });
    foldersCreated.push(projectRoot);

    for (const rel of MOCHA_FOLDERS) {
      const full = path.join(projectRoot, rel);
      fs.mkdirSync(full, { recursive: true });
      foldersCreated.push(full);
    }

    const write = (rel, content) => {
      const full = path.join(projectRoot, rel);
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, content, 'utf8');
      filesCreated.push(full);
    };

    write('package.json',                buildPackageJson(trimmedName));
    write('.mocharc.cjs',                buildMochaRc());
    write('.gitignore',                  buildGitignore());
    write('README.md',                   buildReadme(trimmedName, description));
    write('tests/suites/example.spec.js', buildExampleSpec(trimmedName));

  } catch (err) {
    try {
      if (fs.existsSync(projectRoot)) fs.rmSync(projectRoot, { recursive: true, force: true });
    } catch { /* ignore rollback error */ }

    if (err.statusCode === 400) throw err;
    if (err.code === 'ENOSPC')       throw scaffoldError('Đĩa cứng đầy.', 'DISK_FULL');
    if (err.code === 'ENAMETOOLONG') throw scaffoldError('Đường dẫn quá dài.', 'PATH_TOO_LONG');
    if (err.code === 'EACCES' || err.code === 'EPERM') {
      throw scaffoldError(`Không có quyền tạo thư mục project.`, 'PERMISSION_DENIED');
    }

    const w = new Error(`Lỗi tạo project: ${err.message}`);
    w.statusCode = 500;
    throw w;
  }

  return {
    projectRoot,
    katalon_project_path: projectRoot, // field name kept for DB compat
    foldersCreated,
    filesCreated,
  };
}

// Keep the old function name as an alias so generateKatalonProject.usecase.js works without changes.
const generateKatalonProject = generateMochaProject;

module.exports = {
  generateMochaProject,
  generateKatalonProject,
  validateScaffoldInputs,
  MOCHA_FOLDERS,
};
